name: shelem_shomar
description: A Shelem counter app.
version: 1.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  jalali_date: ^0.1.5
  intl: ^0.15.8
  intl_translation: ^0.17.7
  sqflite: any
  path_provider: any
  flutter_slidable_list_view: ^1.2.5
  image_picker: ^0.6.1+8
  url_launcher: ^5.1.3
  flutter_html: ^0.8.2
  gen_lang: ^0.1.2
  shared_preferences: ^0.5.1+2
  package_info: ^0.4.0+6
  get_version: ^0.1.0
  wave: ^0.0.8
  share_extend: ^1.0.9
  file_picker: ^1.4.2
  flutter_spinkit: "^2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/person-icon.jpg
    - assets/icon.png
    - assets/images/camera_black.png
    - assets/images/one.png
    - assets/images/two.png
    - assets/images/three.png

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazir-FD.ttf
        - asset: assets/fonts/Vazir-Bold-FD.ttf
    - family: opensans
      fonts:
        - asset: assets/fonts/opensans.ttf